spring:
  application:
    name: configuration-microservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leoluzh/ecommerce-microservice-configuration
          clone-on-start: true
          default-label: main

server:
  port: 8888
  shutdown: graceful