spring:
  application:
    name: eureka-service-registry

server:
    port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url: http://localhost:8761/eureka, http://localhost:8762/eureka
    eureka-server-connect-timeout-seconds:
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
