spring:
  application:
    name: product-microservice

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: *